export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOADING = "USER_LOADING";

export const SAVE_TO_STORAGE_REQUEST = 'SAVE_TO_STORAGE_REQUEST';
export const SAVE_TO_STORAGE_SUCCESS = 'SAVE_TO_STORAGE_SUCCESS';
export const SAVE_TO_STORAGE_ERROR = 'SAVE_TO_STORAGE_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
