export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SAVE_TO_STORAGE_REQUEST = 'SAVE_TO_STORAGE_REQUEST';
export const SAVE_TO_STORAGE_SUCCESS = 'SAVE_TO_STORAGE_SUCCESS';
export const SAVE_TO_STORAGE_ERROR = 'SAVE_TO_STORAGE_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
